# Builds and publishes the Monaco Editor website

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build-website
  displayName: 'Build website'

- script: |
    ./build/publish-website.sh
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
  displayName: 'Publish website'